version: '3.8'

services:
  pdf-to-text:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped
    
  # Para producción, usar esta configuración:
  pdf-to-text-prod:
    build: .
    ports:
      - "80:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: always
    profiles:
      - production 